<img src="images/usm.jpg" width="480" height="240" align="left"/>

# MAT281 - Laboratorio N°02

## Objetivos de la clase

* Reforzar los conceptos básicos de numpy.

## Contenidos

* [Problema 01](#p1)
* [Problema 02](#p2)
* [Problema 03](#p3)

<a id='p1'></a>

## Problema 01

Una **media móvil simple** (SMA) es el promedio de los últimos $k$ datos anteriores, es decir, sea $a_1$,$a_2$,...,$a_n$ un arreglo $n$-dimensional, entonces la SMA se define por:

$$sma(k) =\dfrac{1}{k}(a_{n}+a_{n-1}+...+a_{n-(k-1)}) = \dfrac{1}{k}\sum_{i=0}^{k-1}a_{n-i}  $$ 


Por otro lado podemos definir el SMA con una venta móvil de $n$ si el resultado nos retorna la el promedio ponderado avanzando de la siguiente forma:

* $a = [1,2,3,4,5]$, la SMA con una ventana de $n=2$ sería:


    * sma(2): [mean(1,2),mean(2,3),mean(3,4)] = [1.5, 2.5, 3.5, 4.5]
    * sma(3): [mean(1,2,3),mean(2,3,4),mean(3,4,5)] = [2.,3.,4.]


Implemente una función llamada `sma` cuyo input sea un arreglo unidimensional $a$ y un entero $n$, y cuyo ouput retorne el valor de la media móvil simple sobre el arreglo de la siguiente forma:

* **Ejemplo**: *sma([5,3,8,10,2,1,5,1,0,2], 2)* = $[4. , 5.5, 9. , 6. , 1.5, 3. , 3. , 0.5, 1. ]$

En este caso, se esta calculando el SMA para un arreglo con una ventana de $n=2$.

**Hint**: utilice la función `numpy.cumsum`

In [145]:
import numpy as np
def sma(arreglo,n)->np.array:
    """
    sma(arreglo,n)
    
    Calcula la media móvil simple de n datos anteriores del arreglo
    
    Parameters
    ----------
    arreglo: array
            Arreglo con valores númericos
            
    Returns
    -------
    output : array
            Arreglo con las medias móviles simples
            
    Examples
    --------
    >>> sma([1,2,3,4,5],3)
    [2.0, 3.0, 4.0]
    
    >>>sma([5,3,8,10,2,1,5,1,0,2], 2)
    [4.0, 5.5, 9.0, 6.0, 1.5, 3.0, 3.0, 0.5, 1.0]
    """
    i=0 # Contador
    dev=[] # Arreglo a devolver
    sumas=np.cumsum(arreglo) # arreglo con todas las sumas acumuladas del arreglo
    promedio=0 # variable para guardar el promedio de n variables del arreglo
    sup=0  # suma de n valores
    inf=0  # suma de n-i valores, esta sera la cola inferior de la sumatoria
    while i<=len(arreglo)-n: #itero la cantidad especificada
        if i==0: #caso en que no deba eleminar una cola inferior de la suma
            sup=sumas[n-1]
            inf=0
            promedio=(sup-inf)/n
            dev.append(promedio)
            i+=1
        if i>0: # resto de casos donde si debo eliminar una cola de la suma total de elementos
            sup=sumas[i+n-1]
            inf=sumas[i-1]
            promedio = (sup-inf)/n
            dev.append(promedio)
            i+=1
    
    return dev

[2.0, 3.0, 4.0]
[4.0, 5.5, 9.0, 6.0, 1.5, 3.0, 3.0, 0.5, 1.0]


<a id='p2'></a>

## Problema 02

La función **strides($a,n,p$)**, corresponde a transformar un arreglo unidimensional $a$ en una matriz de $n$ columnas, en el cual las filas se van construyendo desfasando la posición del arreglo en $p$ pasos hacia adelante.

* Para el arreglo unidimensional $a$ = [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], la función strides($a,4,2$), corresponde a crear una matriz de $4$ columnas, cuyos desfaces hacia adelante se hacen de dos en dos. 

El resultado tendría que ser algo así:$$\begin{pmatrix}
 1& 2 &3 &4 \\ 
 3&  4&5&6 \\ 
 5& 6 &7 &8 \\ 
 7& 8 &9 &10 \\ 
\end{pmatrix}$$


Implemente una función llamada `strides(a,4,2)` cuyo input sea un arreglo unidimensional y retorne la matriz de $4$ columnas, cuyos desfaces hacia adelante se hacen de dos en dos. 

* **Ejemplo**: *strides($a$,4,2)* =$\begin{pmatrix}
 1& 2 &3 &4 \\ 
 3&  4&5&6 \\ 
 5& 6 &7 &8 \\ 
 7& 8 &9 &10 \\ 
\end{pmatrix}$


In [147]:
import numpy as np
arr=[1,2,3,4,5,6,7,8,9,10]
def strides(a,n,p)->np.array:
    """
    strides(a,n,p)
    
    Transforma un arreglo en una matriz de n columnas,
    en la cual las filas se van construyendo desfasando
    la posición del arreglo en  𝑝  pasos hacia adelante.
    
    Parameters
    -----------
    a : array
        Arreglo que se desea transformar
    n : int
        Cantidad de columnas de la matriz
    p : int
        Desface para las filas
        
    Returns
    --------
    output : np.array((n,n))
    
    Examples
    --------
    >>>mat=strides(arr,4,2)
    [[ 1.  2.  3.  4.]
     [ 3.  4.  5.  6.]
     [ 5.  6.  7.  8.]
     [ 7.  8.  9. 10.]]
     
    >>>mat=strides(arr,4,1)
    [[1. 2. 3. 4.]
     [2. 3. 4. 5.]
     [3. 4. 5. 6.]
     [4. 5. 6. 7.]]
     
    """
    i=0
    aj=np.zeros((n,n))
    while i<n:
        j=i*p
        aj[i]=a[j:j+n]
        i+=1
        
    return aj
mat=strides(arr,4,2)
print(mat)
mat=strides(arr,4,1)
print(mat)

[[ 1.  2.  3.  4.]
 [ 3.  4.  5.  6.]
 [ 5.  6.  7.  8.]
 [ 7.  8.  9. 10.]]
[[1. 2. 3. 4.]
 [2. 3. 4. 5.]
 [3. 4. 5. 6.]
 [4. 5. 6. 7.]]


In [69]:
import numpy as np
arr=[1,2,3,4,5,6,7,8,9,10]
aj=np.zeros((4,4))
print(aj)
aj[1]=[1,2,3,4]
print(aj)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 0. 0. 0.]
 [1. 2. 3. 4.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


<a id='p3'></a>

## Problema 03


Un **cuadrado mágico** es una matriz de tamaño $n \times n$ de números enteros positivos tal que 
la suma de los números por columnas, filas y diagonales principales sea la misma. Usualmente, los números empleados para rellenar las casillas son consecutivos, de 1 a $n^2$, siendo $n$ el número de columnas y filas del cuadrado mágico.

Si los números son consecutivos de 1 a $n^2$, la suma de los números por columnas, filas y diagonales principales 
es igual a : $$M_{n} = \dfrac{n(n^2+1)}{2}$$
Por ejemplo, 

* $A= \begin{pmatrix}
 4& 9 &2 \\ 
 3&  5&7 \\ 
 8& 1 &6 
\end{pmatrix}$,
es un cuadrado mágico.

* $B= \begin{pmatrix}
 4& 2 &9 \\ 
 3&  5&7 \\ 
 8& 1 &6 
\end{pmatrix}$, no es un cuadrado mágico.

Implemente una función llamada `es_cudrado_magico` cuyo input sea una matriz cuadrada de tamaño $n$ con números consecutivos de $1$ a $n^2$ y cuyo ouput retorne *True* si es un cuadrado mágico o 'False', en caso contrario

* **Ejemplo**: *es_cudrado_magico($A$)* = True, *es_cudrado_magico($B$)* = False

**Hint**: Cree una función que valide la mariz es cuadrada y  que sus números son consecutivos del 1 a $n^2$.

In [159]:
import numpy as np
A=np.zeros((3,3))
B=np.zeros((3,3))
A[0]=[4,9,2]
A[1]=[3,5,7]
A[2]=[8,1,6]
B[0]=[4,2,9]
B[1]=[3,5,7]
B[2]=[8,1,6]
def cuadrada(a)->bool:
    """
    cuadrada(a)
    
    Determina si una matriz es cuadrada
    
    Parameters
    ----------
    a : np.array
        Matriz de numpy
        
    Returns
    --------
    output : bool
        Valor de verdad de que la matriz entregada sea cuadrada
    
    """
    if a.shape[0]!=a.shape[1]: #determina si la matriz es cuadrada
        return False # Retorna falso si no lo es
    return True # Retorna verdadero si, sí lo es
def ordenada(a,n):
        """
    ordenada(a,n)
    
    Determina si la matriz tiene todos los elementos del 1 al n^2, donde n es
    el tamaño de la matriz
    Parameters
    ----------
    a : np.array
        matriz de numpy
    n : int
        Tamaño de la matriz cuadrada
    Returns
    --------
    output : bool
        Valor de verdad de que la matriz contenga los elementos deseados   
    
    
    """
        i=0 #contador
        arr=list(range(1,n**2+1)) #arreglo ordenado de los elementos que la matriz debe tener
        ordenada=np.sort(a,None)  # arreglo ordenado de todos los elementos de la matriz entregada
        while i<n^2:  #recorro los arreglos elemento a elemento
            if arr[i]==ordenada[i]: #compruebo que sean iguales
                i+=1 
            else:return False # si en al menos un elemento no son iguales se retorna False
        return True #si los elementos son igual se retorna True
def magia(a,n):
        """
    magia(a,n)
    
    Se determina si las filas y diagonales principales 
    de la matriz dada suman la constante magica correspondiente a su tamaño
    
    Parameters
    ----------
    a : np.array
        matriz dada candidata a magica
    n : int
        Tamaño de la matriz dada
    Returns
    --------
    output : bool
        Valor de verdad de que la matriz sea magica
    
    """
        magico=n*((n**2)+1)/2 # calculo la constante correspondiente al tamaño de la matriz
        for i in range(n): #contador para recorrer la matriz fila a fila, y colimna a colmna
            if np.sum(a,1)[i]!=magico: #determina si las filas cumplen la condicion
                return False
            if np.sum(a.T,1)[i]!=magico: #determina si las columnas cumples las condiciones
                return False
        if a.trace()!=magico:  #determina si la diagonal principal cumple la condicion
            return False
        if a[::-1].trace()!=magico: #determina si la diagonal secundaria cumple la condicion
            return False
        return True
def es_cuadrado_magico(a)->bool:
        """
    cuadrado_magico(a)
    
    Determina si la matriz dada es magica y retorna un valor de verdad
    
    Parameters
    ----------
    a : np.array
        matriz candidata
        
    Returns
    --------
    output : bool
        Valor de verdad de que la matriz dada sea magica
        
    Examples
    ---------
    >>>print(es_cuadrado_magico(A))
    True
    >>>print(es_cuadrado_magico(B))
    False
    
    
    """
        flag=True
        flag=cuadrada(a)
        if flag==False:
            return False
        largo=a.shape[0]
        flag=ordenada(a,largo)
        if flag==False:
            return False
        flag=magia(a,largo)
        if flag==False:
            return False
        return flag